import json, os

arb_dir = r'd:\etapms\lib\l10n'

new_keys = {
    'en': {
        'employeeLogging': 'Employee Logging',
        'enterEmployeeId': 'Enter Employee ID',
        'enterPassword': 'Enter Password',
        'rememberMe': 'Remember me',
        'logIn': 'Log In',
        'start': 'Start',
        'stop': 'Stop',
        'recentlyLog': 'Recently log',
        'workingHours': 'Working hours',
        'goodMorning': 'Good Morning',
        'workDays': 'WORK DAYS',
        'absenceDays': 'ABSENCE DAYS',
        'publicHolidays': 'PUBLIC HOLIDAYS',
        'workHours': 'WORK HOURS',
        'currentLocation': 'Current Location',
        'present': 'Present',
        'absence': 'Absence',
        'publicHoliday': 'Public Holiday',
        'startWork': 'Start Work',
        'startWorkMessage': 'Are you ready to start your work session for today?',
        'no': 'No',
        'yes': 'Yes',
        'changePasswordSubtitle': 'Update your password to keep your account secure.',
        'enterCurrentPassword': 'Enter Current Password',
        'enterNewPassword': 'Enter New Password',
        'confirmNewPassword': 'Confirm New Password',
        'weak': 'Weak',
        'medium': 'Medium',
        'strong': 'Strong',
        'passwordMustContain': 'Password must contain:',
        'passwordChars': '8+ characters',
        'passwordUppercase': 'Uppercase letter',
        'passwordNumber': 'Number',
        'passwordChangedSuccess': 'Password changed successfully.',
        'selectRequestType': 'Select a request type',
        'selectIssueType': 'Select issue type',
        'request': 'Request',
        'selectDate': 'Select Date',
        'reasonOptional': 'Reason (Optional)',
        'enterReason': 'Enter the reason ...',
        'describeIssue': 'Describe the issue ...',
        'reportIssue': 'Report Issue',
        'requestSubmitted': 'Request submitted successfully.',
        'issueReported': 'Issue reported successfully.',
        'days': 'Days',
        'selectPreferredLanguage': 'Select your preferred language',
        'joinedDate': 'Joined Date',
        'email': 'Email',
        'mobileNumber': 'Mobile Number',
        'whatsAppNumber': 'WhatsApp Number',
    },
    'si': {
        'employeeLogging': 'සේවක පිවිසීම',
        'enterEmployeeId': 'සේවක ID ඇතුළු කරන්න',
        'enterPassword': 'මුරපදය ඇතුළු කරන්න',
        'rememberMe': 'මා මතක තබා ගන්න',
        'logIn': 'පිළිසෙන්න',
        'start': 'ආරම්භ කරන්න',
        'stop': 'නවතන්න',
        'recentlyLog': 'මේත ලොග්',
        'workingHours': 'වැඩ කරන පැය',
        'goodMorning': 'සුභ ඍදැසනක්',
        'workDays': 'වැඩ දින',
        'absenceDays': 'නොපැමිණීමේ දින',
        'publicHolidays': 'රජයේ නිවාඩු',
        'workHours': 'වැඩ කළ පැය',
        'currentLocation': 'වර්තමාන ස්තානය',
        'present': 'පැමිණියේය',
        'absence': 'නොපැමිණීම',
        'publicHoliday': 'රජයේ නිවාඩු',
        'startWork': 'වැඩ ආරම්භ කරන්න',
        'startWorkMessage': 'ඔබ අද වැඩ ආරම්භ කිරීමට සූදානම්ද?',
        'no': 'නැහැ',
        'yes': 'ඔව්',
        'changePasswordSubtitle': 'ඔබගේ ගිණුම ආරක්ෂිතව තබා ගෙනීමට මුරපදය යාවත්කාලීන කරන්න.',
        'enterCurrentPassword': 'වත්මන් මුරපදය ඇතුළු කරන්න',
        'enterNewPassword': 'නව මුරපදය ඇතුළු කරන්න',
        'confirmNewPassword': 'නව මුරපදය තහවුරු කරන්න',
        'weak': 'දුර්ළල',
        'medium': 'මද්‍යම',
        'strong': 'ෂක්තිමත්',
        'passwordMustContain': 'මුරපදය අවෂ්‍ය:',
        'passwordChars': 'අක්ෂර 8+',
        'passwordUppercase': 'ලොකු අකුරු',
        'passwordNumber': 'අංකය',
        'passwordChangedSuccess': 'මුරපදය සාර්තකව වේනස් කරන ලදී.',
        'selectRequestType': 'ඇල්ලීම් වර්ගයක් තෝරන්න',
        'selectIssueType': 'ගැටලු වර්ගය තෝරන්න',
        'request': 'ඇල්ලීම',
        'selectDate': 'දිනය තෝරන්න',
        'reasonOptional': 'හේතුව (අවෂ්‍ය නැත)',
        'enterReason': 'හේතුව ඇතුළු කරන්න ...',
        'describeIssue': 'ගැටලුව ළිස්තර කරන්න ...',
        'reportIssue': 'ගැටලුව වාර්තා කරන්න',
        'requestSubmitted': 'ඇල්ලීම සාර්තකව ඇදිරිපත් කරන ලදී.',
        'issueReported': 'ගැටලුව සාර්තකව වාර්තා කරන ලදී.',
        'days': 'දින',
        'selectPreferredLanguage': 'ඔබේ කැමති භාෂාව තෝරන්න',
        'joinedDate': 'එකතු ළු දිනය',
        'email': 'ළිද්‍යුත් තැපැල',
        'mobileNumber': 'ජංගම දුරකතහන අංකය',
        'whatsAppNumber': 'WhatsApp අංකය',
    },
    'hi': {
        'employeeLogging': 'कर्मचारी लॉगिन',
        'enterEmployeeId': 'कर्मचारी ID दर्ज करें',
        'enterPassword': 'पासवर्ड दर्ज करें',
        'rememberMe': 'मुझे याद रखें',
        'logIn': 'लॉग इन करें',
        'start': 'शुरू करें',
        'stop': 'रोकें',
        'recentlyLog': 'हाल का लॉग',
        'workingHours': 'काम के घंटे',
        'goodMorning': 'सुप्रभात',
        'workDays': 'कार्य दिवस',
        'absenceDays': 'अनुपस्थिति दिवस',
        'publicHolidays': 'सार्वजनिक छुट्टियाँ',
        'workHours': 'कार्य घंटे',
        'currentLocation': 'वर्तमान स्थान',
        'present': 'उपस्थित',
        'absence': 'अनुपस्थित',
        'publicHoliday': 'सार्वजनिक अवकाश',
        'startWork': 'काम शुरू करें',
        'startWorkMessage': 'क्या आप आज का काम शुरू करने के लिए तैयार हैं?',
        'no': 'नहीं',
        'yes': 'हाँ',
        'changePasswordSubtitle': 'अपना खाता सुरक्षित रखने के लिए पासवर्ड अपडेट करें।',
        'enterCurrentPassword': 'वर्तमान पासवर्ड दर्ज करें',
        'enterNewPassword': 'नया पासवर्ड दर्ज करें',
        'confirmNewPassword': 'नया पासवर्ड दोबारा दर्ज करें',
        'weak': 'कमज़ोर',
        'medium': 'मध्यम',
        'strong': 'मजबूत',
        'passwordMustContain': 'पासवर्ड में होना चाहिए:',
        'passwordChars': '8+ अक्षर',
        'passwordUppercase': 'बड़े अक्षर',
        'passwordNumber': 'नंबर',
        'passwordChangedSuccess': 'पासवर्ड सफलतापूर्वक बदला गया।',
        'selectRequestType': 'अनुरोध प्रकार चुनें',
        'selectIssueType': 'समस्या प्रकार चुनें',
        'request': 'अनुरोध',
        'selectDate': 'दिनांक चुनें',
        'reasonOptional': 'कारण (वैकल्पिक)',
        'enterReason': 'कारण दर्ज करें ...',
        'describeIssue': 'समस्या का विवरण दें ...',
        'reportIssue': 'समस्या रिपोर्ट करें',
        'requestSubmitted': 'अनुरोध सफलतापूर्वक सबमिट किया गया।',
        'issueReported': 'समस्या सफलतापूर्वक रिपोर्ट की गई।',
        'days': 'दिन',
        'selectPreferredLanguage': 'अपनी पसंदीदा भाषा चुनें',
        'joinedDate': 'शामिल होने की तारीख',
        'email': 'ईमेल',
        'mobileNumber': 'मोबाइल नंबर',
        'whatsAppNumber': 'WhatsApp नंबर',
    },
    'zh': {
        'employeeLogging': '员工登录',
        'enterEmployeeId': '输入员工ID',
        'enterPassword': '输入密码',
        'rememberMe': '记住我',
        'logIn': '登录',
        'start': '开始',
        'stop': '停止',
        'recentlyLog': '最近日志',
        'workingHours': '工作时间',
        'goodMorning': '早上好',
        'workDays': '工作天数',
        'absenceDays': '缺勤天数',
        'publicHolidays': '公共假日',
        'workHours': '工作小时',
        'currentLocation': '当前位置',
        'present': '出勤',
        'absence': '缺勤',
        'publicHoliday': '公共假日',
        'startWork': '开始工作',
        'startWorkMessage': '您准备好开始今天的工作了吗？',
        'no': '否',
        'yes': '是',
        'changePasswordSubtitle': '更新您的密码以确保账户安全。',
        'enterCurrentPassword': '输入当前密码',
        'enterNewPassword': '输入新密码',
        'confirmNewPassword': '确认新密码',
        'weak': '弱',
        'medium': '中等',
        'strong': '强',
        'passwordMustContain': '密码必须包含：',
        'passwordChars': '8+个字符',
        'passwordUppercase': '大写字母',
        'passwordNumber': '数字',
        'passwordChangedSuccess': '密码更改成功。',
        'selectRequestType': '选择请求类型',
        'selectIssueType': '选择问题类型',
        'request': '请求',
        'selectDate': '选择日期',
        'reasonOptional': '原因（可选）',
        'enterReason': '输入原因 ...',
        'describeIssue': '描述问题 ...',
        'reportIssue': '报告问题',
        'requestSubmitted': '请求已成功提交。',
        'issueReported': '问题已成功报告。',
        'days': '天',
        'selectPreferredLanguage': '选择您的首选语言',
        'joinedDate': '加入日期',
        'email': '电子邮件',
        'mobileNumber': '手机号码',
        'whatsAppNumber': 'WhatsApp号码',
    },
    'ru': {
        'employeeLogging': 'Вход сотрудника',
        'enterEmployeeId': 'Введите ID сотрудника',
        'enterPassword': 'Введите пароль',
        'rememberMe': 'Запомнить меня',
        'logIn': 'Войти',
        'start': 'Начать',
        'stop': 'Стоп',
        'recentlyLog': 'Последние записи',
        'workingHours': 'Рабочие часы',
        'goodMorning': 'Доброе утро',
        'workDays': 'РАБ. ДНИ',
        'absenceDays': 'ДНИ ОТСУТСТВИЯ',
        'publicHolidays': 'ПУБ. ПРАЗДНИКИ',
        'workHours': 'РАБ. ЧАСЫ',
        'currentLocation': 'Текущее местоположение',
        'present': 'Присутствует',
        'absence': 'Отсутствие',
        'publicHoliday': 'Праздничный день',
        'startWork': 'Начать работу',
        'startWorkMessage': 'Вы готовы начать рабочий день?',
        'no': 'Нет',
        'yes': 'Да',
        'changePasswordSubtitle': 'Обновите пароль для безопасности аккаунта.',
        'enterCurrentPassword': 'Введите текущий пароль',
        'enterNewPassword': 'Введите новый пароль',
        'confirmNewPassword': 'Подтвердите новый пароль',
        'weak': 'Слабый',
        'medium': 'Средний',
        'strong': 'Сильный',
        'passwordMustContain': 'Пароль должен содержать:',
        'passwordChars': '8+ символов',
        'passwordUppercase': 'Заглавную букву',
        'passwordNumber': 'Цифру',
        'passwordChangedSuccess': 'Пароль успешно изменён.',
        'selectRequestType': 'Выберите тип запроса',
        'selectIssueType': 'Выберите тип проблемы',
        'request': 'Запрос',
        'selectDate': 'Выберите дату',
        'reasonOptional': 'Причина (необязательно)',
        'enterReason': 'Введите причину ...',
        'describeIssue': 'Опишите проблему ...',
        'reportIssue': 'Сообщить о проблеме',
        'requestSubmitted': 'Запрос успешно отправлен.',
        'issueReported': 'Проблема успешно отправлена.',
        'days': 'Дней',
        'selectPreferredLanguage': 'Выберите предпочтительный язык',
        'joinedDate': 'Дата вступления',
        'email': 'Эл. почта',
        'mobileNumber': 'Номер телефона',
        'whatsAppNumber': 'Номер WhatsApp',
    },
    'th': {
        'employeeLogging': 'การเข้าสู่ระบบพนักงาน',
        'enterEmployeeId': 'ป้อนรหัสพนักงาน',
        'enterPassword': 'ป้อนรหัสผ่าน',
        'rememberMe': 'จดจำฉัน',
        'logIn': 'เข้าสู่ระบบ',
        'start': 'เริ่ม',
        'stop': 'หยุด',
        'recentlyLog': 'บันทึกล่าสุด',
        'workingHours': 'ชั่วโมงทำงาน',
        'goodMorning': 'อรุณสวัสดิ์',
        'workDays': 'วันทำงาน',
        'absenceDays': 'วันขาดงาน',
        'publicHolidays': 'วันหยุดราชการ',
        'workHours': 'ชั่วโมงงาน',
        'currentLocation': 'ตำแหน่งปัจจุบัน',
        'present': 'มาทำงาน',
        'absence': 'ขาดงาน',
        'publicHoliday': 'วันหยุดราชการ',
        'startWork': 'เริ่มทำงาน',
        'startWorkMessage': 'คุณพร้อมที่จะเริ่มการทำงานวันนี้หรือยัง?',
        'no': 'ไม่',
        'yes': 'ใช่',
        'changePasswordSubtitle': 'อัพเดทรหัสผ่านเพื่อรักษาความปลอดภัยบัญชีของคุณ',
        'enterCurrentPassword': 'ป้อนรหัสผ่านปัจจุบัน',
        'enterNewPassword': 'ป้อนรหัสผ่านใหม่',
        'confirmNewPassword': 'ยืนยันรหัสผ่านใหม่',
        'weak': 'อ่อนแอ',
        'medium': 'ปานกลาง',
        'strong': 'แข็งแกร่ง',
        'passwordMustContain': 'รหัสผ่านต้องประกอบด้วย:',
        'passwordChars': '8+ ตัวอักษร',
        'passwordUppercase': 'ตัวพิมพ์ใหญ่',
        'passwordNumber': 'ตัวเลข',
        'passwordChangedSuccess': 'เปลี่ยนรหัสผ่านสำเร็จ',
        'selectRequestType': 'เลือกประเภทคำขอ',
        'selectIssueType': 'เลือกประเภทปัญหา',
        'request': 'คำขอ',
        'selectDate': 'เลือกวันที่',
        'reasonOptional': 'เหตุผล (ไม่บังคับ)',
        'enterReason': 'ป้อนเหตุผล ...',
        'describeIssue': 'อธิบายปัญหา ...',
        'reportIssue': 'รายงานปัญหา',
        'requestSubmitted': 'ส่งคำขอสำเร็จ',
        'issueReported': 'รายงานปัญหาสำเร็จ',
        'days': 'วัน',
        'selectPreferredLanguage': 'เลือกภาษาที่คุณต้องการ',
        'joinedDate': 'วันที่เข้าร่วม',
        'email': 'อีเมล',
        'mobileNumber': 'หมายเลขโทรศัพท์มือถือ',
        'whatsAppNumber': 'หมายเลข WhatsApp',
    },
}

for locale, keys in new_keys.items():
    filepath = os.path.join(arb_dir, f'app_{locale}.arb')
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    added = 0
    for key, value in keys.items():
        if key not in data:
            data[key] = value
            added += 1
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'Updated {locale}: added {added} keys')

print('Done!')
